<?php

namespace HomeBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfluencerRepository extends \Doctrine\ORM\EntityRepository
{

}
