#CONCERT
admin_homepage:
    path:     /concert
    defaults: { _controller: AdminBundle:Concert:index }
admin_concert_delete:
    path:     /concert/delete
    defaults: { _controller: AdminBundle:Concert:delete }
admin_concert_edit:
    path:     /concert/edit
    defaults: { _controller: AdminBundle:Concert:edit }
admin_concert_change_affiche:
    path:     /concert/change_affiche
    defaults: { _controller: AdminBundle:Concert:changeAffiche }

#news letter
admin_newsletter:
    path:     /newsletter
    defaults: { _controller: AdminBundle:NewsLetter:index }
admin_newsletter_sent:
    path:     /newsletter/sent
    defaults: { _controller: AdminBundle:NewsLetter:sent }
admin_newsletter_delete:
    path:     /newsletter/delete/{newsletter}
    defaults: { _controller: AdminBundle:NewsLetter:delete }
    requirements:
        newsletter: \d+

#ARTISTE
admin_artiste:
    path:     /artiste
    defaults: { _controller: AdminBundle:Artiste:index }
admin_artiste_edit:
    path:     /artiste/edit
    defaults: { _controller: AdminBundle:Artiste:edit }
admin_artiste_delete:
    path:     /artiste/delete
    defaults: { _controller: AdminBundle:Artiste:delete }

#COMMENTAIRE
admin_commentaire:
    path:     /commentaire
    defaults: { _controller: AdminBundle:Commentaire:index }
admin_commentaire_delete:
    path:     /commentaire/delete
    defaults: { _controller: AdminBundle:Commentaire:delete }


#CONNEXION
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Account:login }

admin_change_password:
    path:     /change_password
    defaults: { _controller: AdminBundle:Account:changePassword }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

admin_create:
    path:     /create
    defaults: { _controller: AdminBundle:Account:create }