#Product
admin_homepage:
    path:     /product
    defaults: { _controller: AdminBundle:Product:index }
admin_product_delete:
    path:     /product/delete
    defaults: { _controller: AdminBundle:Product:delete }
admin_product_add:
    path:     /product/add
    defaults: { _controller: AdminBundle:Product:add }

#Stock
admin_stock:
    path:     /stock
    defaults: { _controller: AdminBundle:Stock:index }
admin_stock_delete:
    path:     /stock/delete
    defaults: { _controller: AdminBundle:Stock:delete }
admin_stock_add:
    path:     /stock/add
    defaults: { _controller: AdminBundle:Stock:add }

#Dashboard
admin_dashboard:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

#CONNEXION
admin_login:
    path:     /
    defaults: { _controller: AdminBundle:Account:login }

admin_change_password:
    path:     /change_password
    defaults: { _controller: AdminBundle:Account:changePassword }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

admin_create:
    path:     /create
    defaults: { _controller: AdminBundle:Account:create }