#Influenceur
admin_homepage:
    path:     /influencer
    defaults: { _controller: AdminBundle:Influencer:index }
admin_influencer_delete:
    path:     /influencer/delete
    defaults: { _controller: AdminBundle:Influencer:delete }
admin_influencer_see:
    path:     /influencer/{influencer}
    defaults: { _controller: AdminBundle:Influencer:see }
    requirements:
        influencer: \d+

#news letter
admin_message:
    path:     /message
    defaults: { _controller: AdminBundle:NewsLetter:index }
admin_message_sent:
    path:     /message/sent
    defaults: { _controller: AdminBundle:NewsLetter:sent }
admin_message_delete:
    path:     /message/delete/{message}
    defaults: { _controller: AdminBundle:NewsLetter:delete }
    requirements:
        message: \d+

#COMMENTAIRE
admin_commentaire:
    path:     /commentaire
    defaults: { _controller: AdminBundle:Contact:index }
admin_commentaire_delete:
    path:     /commentaire/delete
    defaults: { _controller: AdminBundle:Contact:delete }

#ACTIVITY
admin_activity:
    path:     /activity
    defaults: { _controller: AdminBundle:Activity:index }
admin_activity_add:
    path:     /activity/add
    defaults: { _controller: AdminBundle:Activity:add }
admin_activity_delete:
    path:     /activity/delete
    defaults: { _controller: AdminBundle:Activity:delete }

#PARTNERSHIP TYPE
admin_partnership_type:
    path:     /partnership_type
    defaults: { _controller: AdminBundle:PartnershipType:index }
admin_partnership_type_add:
    path:     /partnership_type/add
    defaults: { _controller: AdminBundle:PartnershipType:add }
admin_partnership_type_delete:
    path:     /partnership_type/delete
    defaults: { _controller: AdminBundle:PartnershipType:delete }


#CONNEXION
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Account:login }

admin_change_password:
    path:     /change_password
    defaults: { _controller: AdminBundle:Account:changePassword }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

admin_create:
    path:     /create
    defaults: { _controller: AdminBundle:Account:create }