#Product
admin_homepage:
    path:     /produit
    defaults: { _controller: AdminBundle:Product:index }
admin_produit_delete:
    path:     /produit/delete/{id}
    defaults: { _controller: AdminBundle:Product:delete }
    requirements:
        id: \d+
admin_produit_add:
    path:     /produit/add
    defaults: { _controller: AdminBundle:Product:add }

#Dashboard
admin_dashboard:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

#CONNEXION
admin_login:
    path:     /
    defaults: { _controller: AdminBundle:Account:login }

admin_change_password:
    path:     /change_password
    defaults: { _controller: AdminBundle:Account:changePassword }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

# USER
admin_create:
    path:     /create
    defaults: { _controller: AdminBundle:Account:create }

admin_user:
    path:     /user
    defaults: { _controller: AdminBundle:Account:createUser }

admin_modify_user:
    path:     /user/modify/{id}
    defaults: { _controller: AdminBundle:Account:modifyUser }
    requirements:
        id: \d+

admin_delete_user:
    path:     /user/delete/{id}
    defaults: { _controller: AdminBundle:Account:deleteUser }
    requirements:
        id: \d+

admin_block_user:
    path:     /user/block/{id}
    defaults: { _controller: AdminBundle:Account:blockUser }
    requirements:
        id: \d+

admin_unblock_user:
    path:     /user/unblock/{id}
    defaults: { _controller: AdminBundle:Account:unblockUser }
    requirements:
        id: \d+
# STOCK
admin_stock:
    path:     /produit/{id}
    defaults: { _controller: AdminBundle:Stock:index }
    requirements:
        id: \d+
admin_stock_add:
    path:     /produit/{id}/add
    defaults: { _controller: AdminBundle:Stock:add }
    requirements:
        id: \d+
admin_stock_modify:
    path:     /produit/modify_stock/{id}
    defaults: { _controller: AdminBundle:Stock:modify }
    requirements:
        id: \d+
admin_stock_delete:
    path:     /produit/delete_stock/{id}
    defaults: { _controller: AdminBundle:Stock:delete }
    requirements:
        id: \d+