#CONCERT
admin_concert:
    path:     /concert
    defaults: { _controller: AdminBundle:Concert:index }
admin_concert_delete:
    path:     /concert/delete
    defaults: { _controller: AdminBundle:Concert:delete }
admin_concert_edit:
    path:     /concert/edit
    defaults: { _controller: AdminBundle:Concert:edit }
admin_concert_change_affiche:
    path:     /concert/change_affiche
    defaults: { _controller: AdminBundle:Concert:changeAffiche }
admin_command_user:
    path:     /command/{name}-{user}
    defaults: { _controller: AdminBundle:Command:userCommand }
    requirements:
        name: .+
        user: \d+

#CONNEXION
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Account:login }

admin_change_password:
    path:     /change_password
    defaults: { _controller: AdminBundle:Account:changePassword }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

admin_create:
    path:     /create
    defaults: { _controller: AdminBundle:Account:create }