#CONCERT
admin_homepage:
    path:     /concert
    defaults: { _controller: AdminBundle:Concert:index }
admin_concert_delete:
    path:     /concert/delete
    defaults: { _controller: AdminBundle:Concert:delete }
admin_concert_edit:
    path:     /concert/edit
    defaults: { _controller: AdminBundle:Concert:edit }
admin_concert_change_affiche:
    path:     /concert/change_affiche
    defaults: { _controller: AdminBundle:Concert:changeAffiche }

#CLIENT
admin_client:
    path:     /client
    defaults: { _controller: AdminBundle:Client:index }
admin_client_reservation:
    path:     /client/reservation/{client}
    defaults: { _controller: AdminBundle:Client:reservation }
    requirements:
        client: \d+
admin_client_edit:
    path:     /client/edit
    defaults: { _controller: AdminBundle:Client:edit }
admin_client_delete:
    path:     /client/delete
    defaults: { _controller: AdminBundle:Client:delete }

#SALE
admin_salle:
    path:     /salle
    defaults: { _controller: AdminBundle:Salle:index }
admin_salle_edit:
    path:     /salle/edit
    defaults: { _controller: AdminBundle:Salle:edit }
admin_salle_delete:
    path:     /salle/delete
    defaults: { _controller: AdminBundle:Salle:delete }

#ARTISTE
admin_artiste:
    path:     /artiste
    defaults: { _controller: AdminBundle:Artiste:index }
admin_artiste_edit:
    path:     /artiste/edit
    defaults: { _controller: AdminBundle:Artiste:edit }
admin_artiste_delete:
    path:     /artiste/delete
    defaults: { _controller: AdminBundle:Artiste:delete }

#RESERVATION
admin_reservation:
    path:     /reservation/{concert}
    defaults: { _controller: AdminBundle:Reservation:index }
    requirements:
        concert: \d+
admin_reservation_edit:
    path:     /reservation/edit
    defaults: { _controller: AdminBundle:Reservation:edit }
admin_reservation_delete:
    path:     /reservation/delete
    defaults: { _controller: AdminBundle:Reservation:delete }


#CONNEXION
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Account:login }

admin_change_password:
    path:     /change_password
    defaults: { _controller: AdminBundle:Account:changePassword }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

admin_create:
    path:     /create
    defaults: { _controller: AdminBundle:Account:create }