#Courrier
admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Courrier:index }
admin_courrier_delete:
    path:     /courrier/delete/{id}
    defaults: { _controller: AdminBundle:Courrier:delete }
    requirements:
        id: \d+
admin_courrier_details:
    path:     /courrier/{id}
    defaults: { _controller: AdminBundle:Courrier:details }
    requirements:
        id: \d+
admin_courrier_add:
    path:     /courrier/add
    defaults: { _controller: AdminBundle:Courrier:add }
admin_courrier_nottreat:
    path:     /courrier/nottreat
    defaults: { _controller: AdminBundle:Courrier:nottreat }
admin_courrier_archives:
    path:     /courrier/archives
    defaults: { _controller: AdminBundle:Courrier:archives }
admin_set_service:
    path:     /courrier/service/{id}
    defaults: { _controller: AdminBundle:Courrier:setService }
    requirements:
        id: \d+
admin_transfert_service:
    path:     /courrier/transfert/{id}
    defaults: { _controller: AdminBundle:Courrier:transfertToService }
    requirements:
        id: \d+
admin_set_observation:
    path:     /courrier/observation/{id}
    defaults: { _controller: AdminBundle:Courrier:setObservation }
    requirements:
        id: \d+

#Dashboard
admin_dashboard:
    path:     /dashboard
    defaults: { _controller: AdminBundle:Dashboard:index }

#CONNEXION
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Account:login }

admin_change_password:
    path:     /change_password
    defaults: { _controller: AdminBundle:Account:changePassword }

admin_logout:
    path:     /logout
    defaults: { _controller: AdminBundle:Account:logout }

# USER
admin_create:
    path:     /create
    defaults: { _controller: AdminBundle:Account:create }

admin_user:
    path:     /user
    defaults: { _controller:    AdminBundle:Account:createUser }

admin_modify_user:
    path:     /user/modify/{id}
    defaults: { _controller: AdminBundle:Account:modifyUser }
    requirements:
        id: \d+

admin_delete_user:
    path:     /user/delete/{id}
    defaults: { _controller: AdminBundle:Account:deleteUser }
    requirements:
        id: \d+