admin:
    resource: '@AdminBundle/Resources/config/routing.yml'
    prefix: /admin

home:
    resource: '@HomeBundle/Resources/config/routing.yml'
    prefix: /

auth:
    resource: '@AuthenticationBundle/Resources/config/routing.yml'
    prefix: /