<?php

namespace AuthenticationBundle\Repository;
use Facebook\GraphNodes\GraphUser;
use HomeBundle\Entity\Command;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function addFacebookUser(GraphUser $user){

    }

    public function getPayedUser(){
        $qb = $this->createQueryBuilder("u");
        $qb->innerJoin(Command::class,"c")
            ->where("c.user = u.id")
            ->andWhere("c.isPayed = 1")
            ->orderBy("c.createdAt","asc")
        ;
        return $qb->getQuery()->getResult();
    }
}
