home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Home:index }

home_login:
    path:     /login
    defaults: { _controller: HomeBundle:Home:login }

home_save_email:
    path:     /save_email
    defaults: { _controller: HomeBundle:Home:subscribe }

home_register:
    path:     /register
    defaults: { _controller: HomeBundle:Home:register }

home_change_password:
    path:     /change_password
    defaults: { _controller: HomeBundle:Home:changePassword }

home_forgot_password:
    path:     /forgot_password
    defaults: { _controller: HomeBundle:Home:forgotPassword }

home_commentaire:
    path:     /comment
    defaults: { _controller: HomeBundle:Home:comment }
home_reservation:
    path:     /reservation
    defaults: { _controller: HomeBundle:Reservation:index }
home_reservation_directe:
    path:     /reservation/directe
    defaults: { _controller: HomeBundle:Reservation:reservationDirecte }
home_reservation_normale:
    path:     /reservation/normale
    defaults: { _controller: HomeBundle:Reservation:reservation }
home_reservation_edit:
    path:     /reservation/edit
    defaults: { _controller: HomeBundle:Reservation:edit }
home_dashboard:
    path:     /dashboard
    defaults: { _controller: HomeBundle:Home:userDashBoard }