home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Home:index }

home_about:
    path:     /about
    defaults: { _controller: HomeBundle:Home:about }

home_contact:
    path:     /contact
    defaults: { _controller: HomeBundle:Home:contact }

home_influencer:
    path:     /influencer
    defaults: { _controller: HomeBundle:Home:influencer }

home_login:
    path:     /login
    defaults: { _controller: HomeBundle:Account:login }

home_register:
    path:     /register
    defaults: { _controller: HomeBundle:Account:register }

home_change_password:
    path:     /change_password
    defaults: { _controller: HomeBundle:Account:changePassword }

home_forgot_password:
    path:     /forgot_password
    defaults: { _controller: HomeBundle:Account:forgotPassword }